<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Sekolah;
use Illuminate\Support\Facades\DB;

class SekolahSeeder extends Seeder
{
    /**
     * Data sekolah bersumber dari file sekolah.xlsx (86 baris).
     * Latitude & longitude dikonversi dari format string ke decimal.
     * Sekolah tanpa koordinat (TK, PKBM, LKP, dll) dibiarkan null — kolom sudah nullable.
     */
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        Sekolah::truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $dataSekolah = [
            ['id' => 1, 'jenjang_id' => 3, 'nama_sekolah' => 'SD NEGERI 2 TAPULAGA', 'npsn' => '40400481', 'status' => 'Negeri', 'alamat' => 'Tapulaga, Kec. Soropia, Kab. Konawe', 'akreditasi' => 'B', 'latitude' => -3.92670000, 'longitude' => 122.64010000, 'img' => 'sdn2tapulaga.jpg'],
            ['id' => 2, 'jenjang_id' => 3, 'nama_sekolah' => 'SD NEGERI BAJO INDAH', 'npsn' => '40400195', 'status' => 'Negeri', 'alamat' => 'Bajo Indah, Kec. Soropia, Kab. Konawe', 'akreditasi' => 'B', 'latitude' => -3.92774700, 'longitude' => 122.64500500, 'img' => 'sdnbajoindah.jpg'],
            ['id' => 4, 'jenjang_id' => 3, 'nama_sekolah' => 'SD NEGERI 2 BOKORI', 'npsn' => '40400541', 'status' => 'Negeri', 'alamat' => 'Mekar, Kec. Soropia, Kab. Konawe', 'akreditasi' => 'B', 'latitude' => -3.92443400, 'longitude' => 122.65254400, 'img' => 'sdn2bokori.jpg'],
            ['id' => 5, 'jenjang_id' => 3, 'nama_sekolah' => 'SD NEGERI 1 BOKORI', 'npsn' => '40400342', 'status' => 'Negeri', 'alamat' => 'Bokori, Kec. Soropia, Kab. Konawe', 'akreditasi' => 'C', 'latitude' => -3.92481500, 'longitude' => 122.66426900, 'img' => 'sdn1bokori.jpg'],
            ['id' => 6, 'jenjang_id' => 4, 'nama_sekolah' => 'MIS Al-IKHLAS BAJOE', 'npsn' => '69941401', 'status' => 'Swasta', 'alamat' => 'Jl. Poros Kendari-Toronipa, Kec. Soropia, Kab. Konawe', 'akreditasi' => 'C', 'latitude' => -3.92545000, 'longitude' => 122.65852300, 'img' => 'misalikhlasbajoe.jpg'],
            ['id' => 7, 'jenjang_id' => 3, 'nama_sekolah' => 'SD NEGERI 1 TAPULAGA', 'npsn' => '40400507', 'status' => 'Negeri', 'alamat' => 'Sorue Jaya, Kec. Soropia, Kab. Konawe', 'akreditasi' => 'B', 'latitude' => -3.93731000, 'longitude' => 122.62614400, 'img' => 'sdn1tapulaga.jpg'],
            ['id' => 8, 'jenjang_id' => 3, 'nama_sekolah' => 'SD NEGERI 2 TORONIPA', 'npsn' => '40400486', 'status' => 'Negeri', 'alamat' => 'Toronipa, Kec. Soropia, Kab. Konawe', 'akreditasi' => 'B', 'latitude' => -3.91031300, 'longitude' => 122.65954000, 'img' => 'sdn2toronipa.jpg'],
            ['id' => 9, 'jenjang_id' => 3, 'nama_sekolah' => 'SD NEGERI 3 SOROPIA', 'npsn' => '40400184', 'status' => 'Negeri', 'alamat' => 'Soropia, Kec. Soropia, Kab. Konawe', 'akreditasi' => 'B', 'latitude' => -3.90034700, 'longitude' => 122.58160000, 'img' => 'sdn3soropia.jpg'],
            ['id' => 10, 'jenjang_id' => 5, 'nama_sekolah' => 'SMP NEGERI 1 SOROPIA', 'npsn' => '40403130', 'status' => 'Negeri', 'alamat' => 'Jl. Pendidikan, Kec. Soropia, Kab. Konawe', 'akreditasi' => 'B', 'latitude' => -3.90934700, 'longitude' => 122.65854300, 'img' => 'smpn1soropia.jpg'],
            ['id' => 11, 'jenjang_id' => 5, 'nama_sekolah' => 'SMP NEGERI 2 SOROPIA', 'npsn' => '40400267', 'status' => 'Negeri', 'alamat' => 'Jl. Pramuka No.117, Kec. Soropia, Kab. Konawe', 'akreditasi' => 'C', 'latitude' => -3.89844800, 'longitude' => 122.57637300, 'img' => 'smpn2soropia.jpg'],
            ['id' => 12, 'jenjang_id' => 7, 'nama_sekolah' => 'SMAN 1 SOROPIA', 'npsn' => '40402860', 'status' => 'Negeri', 'alamat' => 'Jl. Poros Kendari-Soropia, Kec. Soropia, Kab. Konawe', 'akreditasi' => 'B', 'latitude' => -3.90055800, 'longitude' => 122.58398300, 'img' => 'sman1soropia.jpg'],
            ['id' => 13, 'jenjang_id' => 3, 'nama_sekolah' => 'SD NEGERI SATU ATAP 2 SOROPIA', 'npsn' => '40403129', 'status' => 'Negeri', 'alamat' => 'Desa Saponda, Kec. Soropia, Kab. Konawe', 'akreditasi' => 'B', 'latitude' => -3.97954500, 'longitude' => 122.76183500, 'img' => 'sdnsatap2soropia.jpg'],
            ['id' => 14, 'jenjang_id' => 5, 'nama_sekolah' => 'SMP NEGERI SATU ATAP 2 SOROPIA', 'npsn' => '40403129', 'status' => 'Negeri', 'alamat' => 'Desa Saponda, Kec. Soropia, Kab. Konawe', 'akreditasi' => 'B', 'latitude' => -3.97969800, 'longitude' => 122.76159500, 'img' => 'smpnsatap2soropia.jpg'],
            ['id' => 15, 'jenjang_id' => 3, 'nama_sekolah' => 'SD NEGERI SAWAPUDO', 'npsn' => '40400282', 'status' => 'Negeri', 'alamat' => 'Sawapudo, Kec. Soropia, Kab. Konawe', 'akreditasi' => 'C', 'latitude' => -3.89679600, 'longitude' => 122.60439800, 'img' => 'sdnsawapudo.jpg'],
            ['id' => 16, 'jenjang_id' => 3, 'nama_sekolah' => 'SDN SATAP 19 KONAWE SELATAN', 'npsn' => '40401845', 'status' => 'Negeri', 'alamat' => 'Jl. Bungin Permai, Kec. Tinanggea, Kab. Konawe Selatan', 'akreditasi' => 'C', 'latitude' => -4.48987200, 'longitude' => 122.21809400, 'img' => 'sdn19konsel.jpg'],
            ['id' => 17, 'jenjang_id' => 3, 'nama_sekolah' => 'SD NEGERI 6 TINANGGEA', 'npsn' => '40402133', 'status' => 'Negeri', 'alamat' => 'Jl. Aspol Lama, Kec. Tinanggea, Kab. Konawe Selatan', 'akreditasi' => 'A', 'latitude' => -4.45745900, 'longitude' => 122.22903600, 'img' => 'sdn6tinanggea.jpg'],
            ['id' => 18, 'jenjang_id' => 3, 'nama_sekolah' => 'SD NEGERI 1 TINANGGEA', 'npsn' => '40401940', 'status' => 'Negeri', 'alamat' => 'Jln. Poros Tinanggea-Bombana, Kec. Tinanggea, Kab. Konawe Selatan', 'akreditasi' => 'B', 'latitude' => -4.43892600, 'longitude' => 122.15405000, 'img' => 'sdn1tinanggea.jpg'],
            ['id' => 19, 'jenjang_id' => 3, 'nama_sekolah' => 'SD NEGERI 2 TINANGGEA', 'npsn' => '40401790', 'status' => 'Negeri', 'alamat' => 'Rt.01 Rw.02 Lingkungan II, Kec. Tinanggea, Kab. Konawe Selatan', 'akreditasi' => 'B', 'latitude' => -4.45448400, 'longitude' => 122.22653500, 'img' => 'sdn2tinanggea.jpg'],
            ['id' => 20, 'jenjang_id' => 3, 'nama_sekolah' => 'SD NEGERI 3 TINANGGEA', 'npsn' => '40401986', 'status' => 'Negeri', 'alamat' => 'Jln Poros Lapoa-Tinanggea, Kec. Tinanggea, Kab. Konawe Selatan', 'akreditasi' => 'C', 'latitude' => -4.43414600, 'longitude' => 122.18138000, 'img' => 'sdn3tinanggea.jpg'],
            ['id' => 21, 'jenjang_id' => 3, 'nama_sekolah' => 'SD NEGERI 5 TINANGGEA', 'npsn' => '40402010', 'status' => 'Negeri', 'alamat' => 'Tinanggea, Kec. Tinanggea, Kab. Konawe Selatan', 'akreditasi' => 'A', 'latitude' => -4.45912600, 'longitude' => 122.22879900, 'img' => 'sdn5tinanggea.jpg'],
            ['id' => 22, 'jenjang_id' => 3, 'nama_sekolah' => 'SD NEGERI 7 TINANGGEA', 'npsn' => '40401796', 'status' => 'Negeri', 'alamat' => 'Lapulu, Kec. Tinanggea, Kab. Konawe Selatan', 'akreditasi' => 'B', 'latitude' => -4.47530300, 'longitude' => 122.25897200, 'img' => 'sdn7tinanggea.jpg'],
            ['id' => 23, 'jenjang_id' => 3, 'nama_sekolah' => 'SD NEGERI 8 TINANGGEA', 'npsn' => '40401786', 'status' => 'Negeri', 'alamat' => 'Jl. Tongkol No.01, Kec. Tinanggea, Kab. Konawe Selatan', 'akreditasi' => 'B', 'latitude' => -4.46875500, 'longitude' => 122.29437300, 'img' => 'sdn8tinanggea.jpg'],
            ['id' => 24, 'jenjang_id' => 3, 'nama_sekolah' => 'SD NEGERI 13 TINANGGEA', 'npsn' => '40403689', 'status' => 'Negeri', 'alamat' => 'Wadonggo, Kec. Tinanggea, Kab. Konawe Selatan', 'akreditasi' => 'C', 'latitude' => -4.46668600, 'longitude' => 122.27429400, 'img' => 'sdn13tinanggea.jpg'],
            ['id' => 25, 'jenjang_id' => 3, 'nama_sekolah' => 'SD NEGERI 9 TINANGGEA', 'npsn' => '40401963', 'status' => 'Negeri', 'alamat' => 'Jl. Poros Pelabuhan Torokeku, Kec. Tinanggea, Kab. Konawe Selatan', 'akreditasi' => 'C', 'latitude' => -4.45974500, 'longitude' => 122.23277600, 'img' => 'sdn9tinanggea.jpg'],
            ['id' => 26, 'jenjang_id' => 5, 'nama_sekolah' => 'SMP NEGERI SATU ATAP 19 KONAWE SELATAN', 'npsn' => '40405024', 'status' => 'Negeri', 'alamat' => 'Bungin Permai, Kec. Tinanggea, Kab. Konawe Selatan', 'akreditasi' => 'C', 'latitude' => -4.48987200, 'longitude' => 122.21809400, 'img' => 'smpnsatap19konsel.jpg'],
            ['id' => 27, 'jenjang_id' => 5, 'nama_sekolah' => 'SMP SWASTA WAHDAH ISLAMIYAH', 'npsn' => '70010126', 'status' => 'Swasta', 'alamat' => 'Jl. Poros Tinanggea-Lapulu, Kec. Tinanggea, Kab. Konawe Selatan', 'akreditasi' => 'C', 'latitude' => -4.46250700, 'longitude' => 122.24090200, 'img' => 'smpswahdah.jpg'],
            ['id' => 28, 'jenjang_id' => 6, 'nama_sekolah' => 'MTSN 2 KONAWE SELATAN', 'npsn' => '40405999', 'status' => 'Negeri', 'alamat' => 'Jl. Jend. Sudirman No.69, Kec. Tinanggea, Kab. Konawe Selatan', 'akreditasi' => 'A', 'latitude' => -4.45974500, 'longitude' => 122.23277600, 'img' => 'mtsn2konsel.jpg'],
            ['id' => 29, 'jenjang_id' => 7, 'nama_sekolah' => 'SMAN 19 KONAWE SELATAN', 'npsn' => '40405054', 'status' => 'Negeri', 'alamat' => 'Jl. Tenggiri No.1, Kec. Tinanggea, Kab. Konawe Selatan', 'akreditasi' => 'B', 'latitude' => -4.45974500, 'longitude' => 122.23277600, 'img' => 'sman19konsel.jpg'],
            ['id' => 30, 'jenjang_id' => 7, 'nama_sekolah' => 'SMAN 1 KONAWE SELATAN', 'npsn' => '40401877', 'status' => 'Negeri', 'alamat' => 'Jl. RA Kartini No.420, Kec. Tinanggea, Kab. Konawe Selatan', 'akreditasi' => 'A', 'latitude' => -4.45974500, 'longitude' => 122.23277600, 'img' => 'sman1konsel.jpg'],
            ['id' => 31, 'jenjang_id' => 3, 'nama_sekolah' => 'SD NEGERI 1 WAWONII BARAT', 'npsn' => '40400330', 'status' => 'Negeri', 'alamat' => 'Jl. Poros Pelabuhan Langara, Kec. Wawonii Barat, Kab. Konawe Kepulauan', 'akreditasi' => 'B', 'latitude' => -4.02831500, 'longitude' => 122.98916600, 'img' => 'sdn1wawoniibarat.jpg'],
            ['id' => 32, 'jenjang_id' => 3, 'nama_sekolah' => 'SD NEGERI 2 WAWONII BARAT', 'npsn' => '40400526', 'status' => 'Negeri', 'alamat' => 'Jl. Poros Langara-Lansilowo, Kec. Wawonii Barat, Kab. Konawe Kepulauan', 'akreditasi' => 'A', 'latitude' => -4.02237900, 'longitude' => 122.99854000, 'img' => 'sdn2wawoniibarat.jpg'],
            ['id' => 33, 'jenjang_id' => 3, 'nama_sekolah' => 'SD NEGERI 3 WAWONII BARAT', 'npsn' => '40403098', 'status' => 'Negeri', 'alamat' => 'Jl. Pelabuhan Kel. Langara Laut, Kec. Wawonii Barat, Kab. Konawe Kepulauan', 'akreditasi' => 'B', 'latitude' => -4.02332900, 'longitude' => 122.99038500, 'img' => 'sdn3wawoniibarat.jpg'],
            ['id' => 34, 'jenjang_id' => 3, 'nama_sekolah' => 'SD NEGERI 4 WAWONII BARAT', 'npsn' => '40400177', 'status' => 'Negeri', 'alamat' => 'Lamoluo, Kec. Wawonii Barat, Kab. Konawe Kepulauan', 'akreditasi' => 'B', 'latitude' => -4.02774600, 'longitude' => 122.98994400, 'img' => 'sdn4wawoniibarat.jpg'],
            ['id' => 35, 'jenjang_id' => 3, 'nama_sekolah' => 'SD NEGERI 5 WAWONII BARAT', 'npsn' => '40400305', 'status' => 'Negeri', 'alamat' => 'Jl. Poros Langara-Lansilowo, Kec. Wawonii Barat, Kab. Konawe Kepulauan', 'akreditasi' => 'C', 'latitude' => -4.02274300, 'longitude' => 122.99062500, 'img' => 'sdn5wawoniibarat.jpg'],
            ['id' => 36, 'jenjang_id' => 3, 'nama_sekolah' => 'SD NEGERI 6 WAWONII BARAT', 'npsn' => '40400159', 'status' => 'Negeri', 'alamat' => 'Matabaho, Kec. Wawonii Barat, Kab. Konawe Kepulauan', 'akreditasi' => 'C', 'latitude' => -4.03493800, 'longitude' => 122.99164500, 'img' => 'sdn6wawoniibarat.jpg'],
            ['id' => 37, 'jenjang_id' => 3, 'nama_sekolah' => 'SD NEGERI 7 WAWONII BARAT', 'npsn' => '40400169', 'status' => 'Negeri', 'alamat' => 'Desa Lanowatu, Kec. Wawonii Barat, Kab. Konawe Kepulauan', 'akreditasi' => 'C', 'latitude' => -4.03424900, 'longitude' => 122.99155200, 'img' => 'sdn7wawoniibarat.jpg'],
            ['id' => 38, 'jenjang_id' => 5, 'nama_sekolah' => 'SMP NEGERI 2 WAWONII BARAT', 'npsn' => '40404239', 'status' => 'Negeri', 'alamat' => 'Jl. Poros Langara-Lampeapi KM 3, Kec. Wawonii Barat, Kab. Konawe Kepulauan', 'akreditasi' => 'C', 'latitude' => -4.04421200, 'longitude' => 122.98797800, 'img' => 'smpn2wawoniibarat.jpg'],
            ['id' => 39, 'jenjang_id' => 5, 'nama_sekolah' => 'SMP NEGERI 3 WAWONII BARAT', 'npsn' => '40404084', 'status' => 'Negeri', 'alamat' => 'Jl. Poros Desa Wawolaa, Kec. Wawonii Barat, Kab. Konawe Kepulauan', 'akreditasi' => 'C', 'latitude' => -4.01727600, 'longitude' => 123.04742400, 'img' => 'smpn3wawoniibarat.jpg'],
            ['id' => 40, 'jenjang_id' => 5, 'nama_sekolah' => 'SMP NEGERI 4 WAWONII BARAT', 'npsn' => '69931771', 'status' => 'Negeri', 'alamat' => 'Desa Matabaho, Kec. Wawonii Barat, Kab. Konawe Kepulauan', 'akreditasi' => 'B', 'latitude' => -4.03694500, 'longitude' => 123.01894600, 'img' => 'smpn4wawoniibarat.jpg'],
            ['id' => 41, 'jenjang_id' => 7, 'nama_sekolah' => 'SMAN 1 WAWONII', 'npsn' => '40400243', 'status' => 'Negeri', 'alamat' => 'Desa Mata Langara, Kec. Wawonii Barat, Kab. Konawe Kepulauan', 'akreditasi' => 'B', 'latitude' => -4.02968300, 'longitude' => 122.98621000, 'img' => 'sman1wawonii.jpg'],
            ['id' => 42, 'jenjang_id' => 3, 'nama_sekolah' => 'SD NEGERI 1 TORONIPA', 'npsn' => '40400512', 'status' => 'Negeri', 'alamat' => 'SDN 1 Toronipa, Kec. Soropia, Kab. Konawe', 'akreditasi' => 'B', 'latitude' => -3.90149700, 'longitude' => 122.64357600, 'img' => 'sdn1toronipa.jpg'],
            ['id' => 43, 'jenjang_id' => 3, 'nama_sekolah' => 'SD NEGERI 3 TORONIPA', 'npsn' => '40400185', 'status' => 'Negeri', 'alamat' => 'Kelurahan Toronipa, Kec. Soropia, Kab. Konawe', 'akreditasi' => 'B', 'latitude' => -3.91033500, 'longitude' => 122.65997000, 'img' => 'sdn3toronipa.jpg'],
            ['id' => 44, 'jenjang_id' => 5, 'nama_sekolah' => 'SMP NEGERI 31 KONAWE SELATAN', 'npsn' => '40403328', 'status' => 'Negeri', 'alamat' => 'Jalan Mangga Butu No.1, Kec. Tinanggea, Kab. Konawe Selatan', 'akreditasi' => 'B', 'latitude' => -4.45974500, 'longitude' => 122.23277600, 'img' => 'smpn31konsel.jpg'],
            ['id' => 45, 'jenjang_id' => 5, 'nama_sekolah' => 'SMP NEGERI 1 WAWONII BARAT', 'npsn' => '40400230', 'status' => 'Negeri', 'alamat' => 'Jl. Poros Langara, Kec. Wawonii Barat, Kab. Konawe Kepulauan', 'akreditasi' => 'B', 'latitude' => -4.02324900, 'longitude' => 122.99086500, 'img' => 'smpn1wawoniibarat.jpg'],
            ['id' => 46, 'jenjang_id' => 3, 'nama_sekolah' => 'SD NEGERI 4 TINANGGEA', 'npsn' => '40402110', 'status' => 'Negeri', 'alamat' => 'Desa Lapoa, Kec. Tinanggea, Kab. Konawe Selatan', 'akreditasi' => 'B', 'latitude' => -4.45974500, 'longitude' => 122.23277600, 'img' => 'sdn4tinanggea.jpg'],
            ['id' => 47, 'jenjang_id' => 14, 'nama_sekolah' => 'LKP ANAK NUSANTARA', 'npsn' => 'K9981131', 'status' => 'Swasta', 'alamat' => 'Jln. Poros Tinanggea - Lalembuu', 'akreditasi' => null, 'latitude' => null, 'longitude' => null, 'img' => 'lkpanaknusantara.jpg'],
            ['id' => 48, 'jenjang_id' => 14, 'nama_sekolah' => 'LKP IZDIHAR', 'npsn' => 'K5668616', 'status' => 'Swasta', 'alamat' => 'Jln. Abd.Silondae', 'akreditasi' => null, 'latitude' => null, 'longitude' => null, 'img' => 'lkpizdihar.jpg'],
            ['id' => 49, 'jenjang_id' => 12, 'nama_sekolah' => 'PKBM ANAK NUSANTARA', 'npsn' => 'P9934396', 'status' => 'Swasta', 'alamat' => 'Jl. Jend. Sodirman Blok B', 'akreditasi' => 'B', 'latitude' => null, 'longitude' => null, 'img' => 'pkbmanaknusantara.jpg'],
            ['id' => 50, 'jenjang_id' => 12, 'nama_sekolah' => 'PKBM ARYA LINGUANGE MANDIRI', 'npsn' => 'P9934831', 'status' => 'Swasta', 'alamat' => 'Desa Bungin Permai', 'akreditasi' => 'C', 'latitude' => -4.46740830, 'longitude' => 122.26900170, 'img' => 'pkbmaryalinguangemandiri.jpg'],
            ['id' => 51, 'jenjang_id' => 12, 'nama_sekolah' => 'PKBM WAJAR', 'npsn' => 'P9998282', 'status' => 'Swasta', 'alamat' => 'Jln. Poros Lasuai', 'akreditasi' => 'C', 'latitude' => null, 'longitude' => null, 'img' => 'pkbmwajar.jpg'],
            ['id' => 52, 'jenjang_id' => 13, 'nama_sekolah' => 'SKB TINANGGEA', 'npsn' => 'P9959761', 'status' => 'Negeri', 'alamat' => 'Jln.Poros Andoolo - Tinanggea', 'akreditasi' => 'C', 'latitude' => -4.43970000, 'longitude' => 122.22860000, 'img' => 'skbtinanggea.jpg'],
            ['id' => 53, 'jenjang_id' => 12, 'nama_sekolah' => 'PKBM SAURI LEAMA', 'npsn' => 'P9908576', 'status' => 'Swasta', 'alamat' => 'Saponda Kecamatan Soropia', 'akreditasi' => 'B', 'latitude' => null, 'longitude' => null, 'img' => 'pkbmsaurileama.jpg'],
            ['id' => 54, 'jenjang_id' => 12, 'nama_sekolah' => 'PKBM MADANI', 'npsn' => 'P9959831', 'status' => 'Swasta', 'alamat' => 'Desa Langara Tanjung Batu', 'akreditasi' => 'B', 'latitude' => -4.01201090, 'longitude' => 123.02768260, 'img' => 'pkbmmadani.jpg'],
            ['id' => 55, 'jenjang_id' => 12, 'nama_sekolah' => 'PKBM HANDAYANI', 'npsn' => 'P2964350', 'status' => 'Swasta', 'alamat' => 'JL. Langara', 'akreditasi' => 'B', 'latitude' => -4.04965710, 'longitude' => 123.02638620, 'img' => 'pkbmhandayani.jpg'],
            ['id' => 56, 'jenjang_id' => 13, 'nama_sekolah' => 'SKB WAWONII', 'npsn' => 'P9962961', 'status' => 'Negeri', 'alamat' => 'Jl. Poros Desa Pasir Putih', 'akreditasi' => 'C', 'latitude' => null, 'longitude' => null, 'img' => 'skbwawonii.jpg'],
            ['id' => 57, 'jenjang_id' => 1, 'nama_sekolah' => 'TK ANGIN MAMIRI', 'npsn' => '69761564', 'status' => 'Swasta', 'alamat' => 'MBATOI, SOROPIA', 'akreditasi' => 'B', 'latitude' => -3.90072300, 'longitude' => 122.58098900, 'img' => 'tkanginmamiri.jpg'],
            ['id' => 58, 'jenjang_id' => 1, 'nama_sekolah' => 'TK DHARMA WANITA', 'npsn' => '69761562', 'status' => 'Swasta', 'alamat' => 'DESA TORONIPA', 'akreditasi' => 'B', 'latitude' => null, 'longitude' => null, 'img' => 'tkdharmawanita.jpg'],
            ['id' => 59, 'jenjang_id' => 1, 'nama_sekolah' => 'TK MEKAR JAYA', 'npsn' => '69762354', 'status' => 'Swasta', 'alamat' => 'Desa Mekar', 'akreditasi' => 'B', 'latitude' => null, 'longitude' => null, 'img' => 'tkmekarjaya.jpg'],
            ['id' => 60, 'jenjang_id' => 1, 'nama_sekolah' => 'TK MUTIARA SAPONDA', 'npsn' => '70056365', 'status' => 'Swasta', 'alamat' => 'Desa Saponda', 'akreditasi' => null, 'latitude' => null, 'longitude' => null, 'img' => 'tkmutiarasaponda.jpg'],
            ['id' => 61, 'jenjang_id' => 1, 'nama_sekolah' => 'TK NEGERI SORUE JAYA', 'npsn' => '70037057', 'status' => 'Negeri', 'alamat' => 'Desa Sorue Jaya', 'akreditasi' => 'B', 'latitude' => null, 'longitude' => null, 'img' => 'tknegerisoruejaya.jpg'],
            ['id' => 62, 'jenjang_id' => 1, 'nama_sekolah' => 'TK PGRI LAMBESO', 'npsn' => '69771530', 'status' => 'Swasta', 'alamat' => 'DUSUN II BOKORI', 'akreditasi' => 'C', 'latitude' => null, 'longitude' => null, 'img' => 'tkpgrilambeso.jpg'],
            ['id' => 63, 'jenjang_id' => 1, 'nama_sekolah' => 'TK SINAR TELAGA', 'npsn' => '69902532', 'status' => 'Swasta', 'alamat' => 'Jl. Poros Toronipa-Soropia', 'akreditasi' => 'C', 'latitude' => null, 'longitude' => null, 'img' => 'tksinartelaga.jpg'],
            ['id' => 64, 'jenjang_id' => 1, 'nama_sekolah' => 'TK WONUA MANDARA', 'npsn' => '69762334', 'status' => 'Swasta', 'alamat' => 'SAWAPUDO', 'akreditasi' => 'B', 'latitude' => -3.89700100, 'longitude' => 122.60309200, 'img' => 'tkwonuamandara.jpg'],
            ['id' => 65, 'jenjang_id' => 1, 'nama_sekolah' => 'TKS ATOWATU', 'npsn' => '69761563', 'status' => 'Swasta', 'alamat' => 'POROS ATOWATU-SOROPIA', 'akreditasi' => 'C', 'latitude' => null, 'longitude' => null, 'img' => 'tksatowatu.jpg'],
            ['id' => 66, 'jenjang_id' => 1, 'nama_sekolah' => 'DHARMA WANITA', 'npsn' => '69797229', 'status' => 'Negeri', 'alamat' => 'JL. DRS. H. ABD SILONDAEA', 'akreditasi' => 'B', 'latitude' => -4.44040000, 'longitude' => 122.19560000, 'img' => 'dharmawanita.jpg'],
            ['id' => 67, 'jenjang_id' => 1, 'nama_sekolah' => 'ISLAM AL-KAUTZAR', 'npsn' => '69797194', 'status' => 'Swasta', 'alamat' => 'JL. H.ABD.SILONDAE', 'akreditasi' => 'B', 'latitude' => -4.46213000, 'longitude' => 122.22650000, 'img' => 'islamalkautzar.jpg'],
            ['id' => 68, 'jenjang_id' => 11, 'nama_sekolah' => 'KB Tunas Mekar Lapoa', 'npsn' => '69952610', 'status' => 'Swasta', 'alamat' => 'Blok B, Desa Lapoa', 'akreditasi' => 'B', 'latitude' => -4.44003900, 'longitude' => 122.17945100, 'img' => 'kbtunasmekarlapoa.jpg'],
            ['id' => 69, 'jenjang_id' => 1, 'nama_sekolah' => 'PRATAMA WIDYALAYA DHARMA SANTI LAPOA', 'npsn' => '70033764', 'status' => 'Swasta', 'alamat' => 'JL. POROS LAPOA-BOMBANA KEC. TINANGGEA', 'akreditasi' => 'C', 'latitude' => -4.43990000, 'longitude' => 122.17480000, 'img' => 'pratamawidyalaya.jpg'],
            ['id' => 70, 'jenjang_id' => 2, 'nama_sekolah' => 'RA AT TAQWA', 'npsn' => '69757116', 'status' => 'Swasta', 'alamat' => 'JLN. JEND. SUDIRMAN', 'akreditasi' => 'A', 'latitude' => -4.44500500, 'longitude' => 122.16782100, 'img' => 'raattaqwa.jpg'],
            ['id' => 71, 'jenjang_id' => 2, 'nama_sekolah' => 'RA/BA/TA AISYIYAH PALOTAWO', 'npsn' => '69751773', 'status' => 'Swasta', 'alamat' => 'DESA PALOTAWO', 'akreditasi' => 'C', 'latitude' => -4.37109000, 'longitude' => 122.20842300, 'img' => 'raaisyiyahpalotawo.jpg'],
            ['id' => 72, 'jenjang_id' => 2, 'nama_sekolah' => 'RA/BA/TA AZ ZAHRA', 'npsn' => '69751774', 'status' => 'Swasta', 'alamat' => 'JLN. YOS SUDARSO', 'akreditasi' => 'C', 'latitude' => -4.47621800, 'longitude' => 122.21964500, 'img' => 'raazzahra.jpg'],
            ['id' => 73, 'jenjang_id' => 2, 'nama_sekolah' => 'RA/BA/TA MIFTAHUL ULUM', 'npsn' => '69751775', 'status' => 'Swasta', 'alamat' => 'DESA MOLO INDAH', 'akreditasi' => 'C', 'latitude' => -4.42506400, 'longitude' => 122.29340200, 'img' => 'ramiftahululum.jpg'],
            ['id' => 74, 'jenjang_id' => 2, 'nama_sekolah' => 'RA/BA/TA ULUL ALBAAB', 'npsn' => '69751777', 'status' => 'Swasta', 'alamat' => 'DESA MATANDAHI', 'akreditasi' => 'C', 'latitude' => -4.46682600, 'longitude' => 122.30995600, 'img' => 'raululalbaab.jpg'],
            ['id' => 75, 'jenjang_id' => 1, 'nama_sekolah' => 'TK CEMPAKA ASINGI', 'npsn' => '69852538', 'status' => 'Swasta', 'alamat' => 'JL. POROS ANDOOLO - TINANGGEA', 'akreditasi' => 'B', 'latitude' => null, 'longitude' => null, 'img' => 'tkcempakaasingi.jpg'],
            ['id' => 76, 'jenjang_id' => 11, 'nama_sekolah' => 'KB Bunga Karang', 'npsn' => '69976993', 'status' => 'Swasta', 'alamat' => 'Desa Langara Tangung Batu Kecamatan Wawonii Barat', 'akreditasi' => 'B', 'latitude' => null, 'longitude' => null, 'img' => 'kbbungakarang.jpg'],
            ['id' => 77, 'jenjang_id' => 11, 'nama_sekolah' => 'KB MATABAHO', 'npsn' => '69978313', 'status' => 'Swasta', 'alamat' => 'Desa Matabaho Kec. Wawonii Barat Kab. Konawe Kepulauan', 'akreditasi' => 'C', 'latitude' => -4.03679640, 'longitude' => 123.01948320, 'img' => 'kbmatabaho.jpg'],
            ['id' => 78, 'jenjang_id' => 10, 'nama_sekolah' => 'PAUD Cendekia', 'npsn' => '69935135', 'status' => 'Swasta', 'alamat' => 'Jl. Poros Langara Wawolaa', 'akreditasi' => 'B', 'latitude' => null, 'longitude' => null, 'img' => 'paudcendekia.jpg'],
            ['id' => 79, 'jenjang_id' => 10, 'nama_sekolah' => 'PAUD Ceria Handayani', 'npsn' => '69919599', 'status' => 'Swasta', 'alamat' => 'Jl. Poros Wawobili', 'akreditasi' => 'C', 'latitude' => -4.01054900, 'longitude' => 123.03276600, 'img' => 'paudceriahandayani.jpg'],
            ['id' => 80, 'jenjang_id' => 10, 'nama_sekolah' => 'PAUD Ika Putri Madani', 'npsn' => '69919346', 'status' => 'Swasta', 'alamat' => 'Jl. Poros Langara-Lampeapi', 'akreditasi' => 'A', 'latitude' => -4.03256660, 'longitude' => 122.99120600, 'img' => 'paudikaputrimadani.jpg'],
            ['id' => 81, 'jenjang_id' => 2, 'nama_sekolah' => 'RA Ummu Salamah', 'npsn' => '70050506', 'status' => 'Swasta', 'alamat' => 'Jl. Abdullah RT.004/RW.002', 'akreditasi' => 'C', 'latitude' => null, 'longitude' => null, 'img' => 'raummusalamah.jpg'],
            ['id' => 82, 'jenjang_id' => 1, 'nama_sekolah' => 'TK AL FADILAH', 'npsn' => '69979190', 'status' => 'Swasta', 'alamat' => 'Desa Bukit Permai Kecamatan Wawonii Barat', 'akreditasi' => 'C', 'latitude' => null, 'longitude' => null, 'img' => 'tkalfadilah.jpg'],
            ['id' => 83, 'jenjang_id' => 1, 'nama_sekolah' => 'TK AFI', 'npsn' => '69918544', 'status' => 'Swasta', 'alamat' => 'Jl. Langara Wawolaa', 'akreditasi' => 'B', 'latitude' => -4.02367700, 'longitude' => 122.99615830, 'img' => 'tkafi.jpg'],
            ['id' => 84, 'jenjang_id' => 1, 'nama_sekolah' => 'TK BAHARI', 'npsn' => '69761631', 'status' => 'Swasta', 'alamat' => 'JL. H. Abdullah', 'akreditasi' => 'C', 'latitude' => -4.02034630, 'longitude' => 122.99327780, 'img' => 'tkbahari.jpg'],
            ['id' => 85, 'jenjang_id' => 1, 'nama_sekolah' => 'TK HARAPAN BANGSA', 'npsn' => '69917973', 'status' => 'Swasta', 'alamat' => 'Jl. Poros Langara Iwawo', 'akreditasi' => 'C', 'latitude' => -4.02974310, 'longitude' => 122.98993300, 'img' => 'tkharapanbangsa.jpg'],
            ['id' => 86, 'jenjang_id' => 1, 'nama_sekolah' => 'TK NEGERI PEMBINA WAWONII BARAT', 'npsn' => '69932594', 'status' => 'Negeri', 'alamat' => 'Jl. Poros Langara', 'akreditasi' => 'B', 'latitude' => null, 'longitude' => null, 'img' => 'tknegeripembinawawoniibarat.jpg'],
            ['id' => 87, 'jenjang_id' => 1, 'nama_sekolah' => 'TK Waly Mekar', 'npsn' => '69967181', 'status' => 'Swasta', 'alamat' => 'Desa Kawa-Kawali Kec Wawonii Barat', 'akreditasi' => 'C', 'latitude' => -4.01007530, 'longitude' => 123.02975750, 'img' => 'tkwalymekar.jpg'],
        ];

        foreach ($dataSekolah as $item) {
            Sekolah::create($item);
        }

        $this->command->info('Sukses! 86 data sekolah berhasil dimasukkan (koordinat null untuk sekolah yang belum memiliki data GPS).');
    }
}