<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Sekolah;
use Illuminate\Support\Facades\Schema;

class SekolahSeeder extends Seeder
{
    /**
     * Data sekolah bersumber dari file sekolah (1).csv
     * Latitude & longitude dikonversi dari format string ke decimal.
     * Sekolah tanpa koordinat dibiarkan null.
     */
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        Sekolah::truncate();
        Schema::enableForeignKeyConstraints();
        $dataSekolah = [
            ['id' => 1, 'jenjang_id' => 3, 'nama_sekolah' => 'SD NEGERI 2 TAPULAGA', 'npsn' => '40400481', 'status' => 'Negeri', 'alamat' => 'Tapulaga, Kec. Soropia, Kab. Konawe', 'akreditasi' => 'B', 'latitude' => -3.93571378, 'longitude' => 122.63770969, 'img' => 'sdn2tapulaga.jpg'], // [cite: 1]
            ['id' => 2, 'jenjang_id' => 3, 'nama_sekolah' => 'SD NEGERI BAJO INDAH', 'npsn' => '40400195', 'status' => 'Negeri', 'alamat' => 'Bajo Indah, Kec. Soropia, Kab. Konawe', 'akreditasi' => 'B', 'latitude' => -3.92774700, 'longitude' => 122.64500500, 'img' => 'sdnbajoindah.jpg'], // [cite: 1]
            ['id' => 4, 'jenjang_id' => 3, 'nama_sekolah' => 'SD NEGERI 2 BOKORI', 'npsn' => '40400541', 'status' => 'Negeri', 'alamat' => 'Mekar, Kec. Soropia, Kab. Konawe', 'akreditasi' => 'B', 'latitude' => -3.92443400, 'longitude' => 122.65254400, 'img' => 'sdn2bokori.jpg'], // [cite: 1]
            ['id' => 5, 'jenjang_id' => 3, 'nama_sekolah' => 'SD NEGERI 1 BOKORI', 'npsn' => '40400342', 'status' => 'Negeri', 'alamat' => 'Bokori, Kec. Soropia, Kab. Konawe', 'akreditasi' => 'C', 'latitude' => -3.92481500, 'longitude' => 122.66426900, 'img' => 'sdn1bokori.jpg'], // [cite: 1]
            ['id' => 6, 'jenjang_id' => 4, 'nama_sekolah' => 'MIS Al-IKHLAS BAJOE', 'npsn' => '69941401', 'status' => 'Swasta', 'alamat' => 'Jl. Poros Kendari-Toronipa, Kec. Soropia, Kab. Konawe', 'akreditasi' => 'C', 'latitude' => -3.92545000, 'longitude' => 122.65852300, 'img' => 'misalikhlasbajoe.jpg'], // [cite: 1]
            ['id' => 7, 'jenjang_id' => 3, 'nama_sekolah' => 'SD NEGERI 1 TAPULAGA', 'npsn' => '40400507', 'status' => 'Negeri', 'alamat' => 'Sorue Jaya, Kec. Soropia, Kab. Konawe', 'akreditasi' => 'B', 'latitude' => -3.93731000, 'longitude' => 122.62614400, 'img' => 'sdn1tapulaga.jpg'], // [cite: 2]
            ['id' => 8, 'jenjang_id' => 3, 'nama_sekolah' => 'SD NEGERI 2 TORONIPA', 'npsn' => '40400486', 'status' => 'Negeri', 'alamat' => 'Toronipa, Kec. Soropia, Kab. Konawe', 'akreditasi' => 'B', 'latitude' => -3.91031300, 'longitude' => 122.65954000, 'img' => 'sdn2toronipa.jpg'], // [cite: 2]
            ['id' => 9, 'jenjang_id' => 3, 'nama_sekolah' => 'SD NEGERI 3 SOROPIA', 'npsn' => '40400184', 'status' => 'Negeri', 'alamat' => 'Soropia, Kec. Soropia, Kab. Konawe', 'akreditasi' => 'B', 'latitude' => -3.90034700, 'longitude' => 122.58160000, 'img' => 'sdn3soropia.jpg'], // [cite: 3]
            ['id' => 10, 'jenjang_id' => 5, 'nama_sekolah' => 'SMP NEGERI 1 SOROPIA', 'npsn' => '40403130', 'status' => 'Negeri', 'alamat' => 'Jl. Pendidikan, Kec. Soropia, Kab. Konawe', 'akreditasi' => 'B', 'latitude' => -3.90934700, 'longitude' => 122.65854300, 'img' => 'smpn1soropia.jpg'], // [cite: 3]
            ['id' => 11, 'jenjang_id' => 5, 'nama_sekolah' => 'SMP NEGERI 2 SOROPIA', 'npsn' => '40400267', 'status' => 'Negeri', 'alamat' => 'Jl. Pramuka No.117, Kec. Soropia, Kab. Konawe', 'akreditasi' => 'C', 'latitude' => -3.89844800, 'longitude' => 122.57637300, 'img' => 'smpn2soropia.jpg'], // [cite: 4]
            ['id' => 12, 'jenjang_id' => 7, 'nama_sekolah' => 'SMAN 1 SOROPIA', 'npsn' => '40402860', 'status' => 'Negeri', 'alamat' => 'Jl. Poros Kendari-Soropia, Kec. Soropia, Kab. Konawe', 'akreditasi' => 'B', 'latitude' => -3.90055800, 'longitude' => 122.58398300, 'img' => 'sman1soropia.jpg'], // [cite: 5]
            ['id' => 13, 'jenjang_id' => 3, 'nama_sekolah' => 'SD NEGERI SATU ATAP 2 SOROPIA', 'npsn' => '40403129', 'status' => 'Negeri', 'alamat' => 'Desa Saponda, Kec. Soropia, Kab. Konawe', 'akreditasi' => 'B', 'latitude' => -3.97954500, 'longitude' => 122.76183500, 'img' => 'sdnsatap2soropia.jpg'], // [cite: 6]
            ['id' => 14, 'jenjang_id' => 5, 'nama_sekolah' => 'SMP NEGERI SATU ATAP 1 SOROPIA', 'npsn' => '40404063', 'status' => 'Negeri', 'alamat' => 'Jalan Wisata Desa Tapulaga, Kec. Soropia, Kab. Konawe, Prov. Sulawesi Tenggara', 'akreditasi' => 'B', 'latitude' => -3.93587145, 'longitude' => 122.63770014, 'img' => 'smpnsatuatap1soropia.jpg'], // [cite: 7]
            ['id' => 15, 'jenjang_id' => 5, 'nama_sekolah' => 'SMP NEGERI SATU ATAP 2 SOROPIA', 'npsn' => '40403129', 'status' => 'Negeri', 'alamat' => 'Desa Saponda, Kec. Soropia, Kab. Konawe', 'akreditasi' => 'B', 'latitude' => -3.97969800, 'longitude' => 122.76159500, 'img' => 'smpnsatap2soropia.jpg'], // [cite: 7]
            ['id' => 16, 'jenjang_id' => 3, 'nama_sekolah' => 'SD NEGERI SAWAPUDO', 'npsn' => '40400282', 'status' => 'Negeri', 'alamat' => 'Sawapudo, Kec. Soropia, Kab. Konawe', 'akreditasi' => 'C', 'latitude' => -3.89679600, 'longitude' => 122.60439800, 'img' => 'sdnsawapudo.jpg'], // [cite: 8]
            ['id' => 17, 'jenjang_id' => 3, 'nama_sekolah' => 'SDN SATAP 19 KONAWE SELATAN', 'npsn' => '40401845', 'status' => 'Negeri', 'alamat' => 'Jl. Bungin Permai, Kec. Tinanggea, Kab. Konawe Selatan', 'akreditasi' => 'C', 'latitude' => -4.48987200, 'longitude' => 122.21809400, 'img' => 'sdn19konsel.jpg'], // [cite: 9]
            ['id' => 18, 'jenjang_id' => 3, 'nama_sekolah' => 'SD NEGERI 6 TINANGGEA', 'npsn' => '40402133', 'status' => 'Negeri', 'alamat' => 'Jl. Aspol Lama, Kec. Tinanggea, Kab. Konawe Selatan', 'akreditasi' => 'A', 'latitude' => -4.46037549, 'longitude' => 122.22862152, 'img' => 'sdn6tinanggea.jpg'], // [cite: 9]
            ['id' => 19, 'jenjang_id' => 3, 'nama_sekolah' => 'SD NEGERI 1 TINANGGEA', 'npsn' => '40401940', 'status' => 'Negeri', 'alamat' => 'Jln. Poros Tinanggea-Bombana, Kec. Tinanggea, Kab. Konawe Selatan', 'akreditasi' => 'B', 'latitude' => -4.44512529, 'longitude' => 122.15418754, 'img' => 'sdn1tinanggea.jpg'], // [cite: 10]
            ['id' => 20, 'jenjang_id' => 3, 'nama_sekolah' => 'SD NEGERI 2 TINANGGEA', 'npsn' => '40401790', 'status' => 'Negeri', 'alamat' => 'Rt.01 Rw.02 Lingkungan II, Kec. Tinanggea, Kab. Konawe Selatan', 'akreditasi' => 'B', 'latitude' => -4.45448400, 'longitude' => 122.22653500, 'img' => 'sdn2tinanggea.jpg'], // [cite: 11]
            ['id' => 21, 'jenjang_id' => 3, 'nama_sekolah' => 'SD NEGERI 3 TINANGGEA', 'npsn' => '40401986', 'status' => 'Negeri', 'alamat' => 'Jln Poros Lapoa-Tinanggea, Kec. Tinanggea, Kab. Konawe Selatan', 'akreditasi' => 'C', 'latitude' => -4.44037584, 'longitude' => 122.18127513, 'img' => 'sdn3tinanggea.jpg'], // [cite: 11]
            ['id' => 22, 'jenjang_id' => 3, 'nama_sekolah' => 'SD NEGERI 5 TINANGGEA', 'npsn' => '40402010', 'status' => 'Negeri', 'alamat' => 'Tinanggea, Kec. Tinanggea, Kab. Konawe Selatan', 'akreditasi' => 'A', 'latitude' => -4.45995776, 'longitude' => 122.22877787, 'img' => 'sdn5tinanggea.jpg'], // [cite: 12]
            ['id' => 23, 'jenjang_id' => 3, 'nama_sekolah' => 'SD NEGERI 7 TINANGGEA', 'npsn' => '40401796', 'status' => 'Negeri', 'alamat' => 'Lapulu, Kec. Tinanggea, Kab. Konawe Selatan', 'akreditasi' => 'B', 'latitude' => -4.47723904, 'longitude' => 122.25915588, 'img' => 'sdn7tinanggea.jpg'], // [cite: 12]
            ['id' => 24, 'jenjang_id' => 3, 'nama_sekolah' => 'SD NEGERI 8 TINANGGEA', 'npsn' => '40401786', 'status' => 'Negeri', 'alamat' => 'Jl. Tongkol No.01, Kec. Tinanggea, Kab. Konawe Selatan', 'akreditasi' => 'B', 'latitude' => -4.46973405, 'longitude' => 122.29443159, 'img' => 'sdn8tinanggea.jpg'], // [cite: 13]
            ['id' => 25, 'jenjang_id' => 3, 'nama_sekolah' => 'SD NEGERI 13 TINANGGEA', 'npsn' => '40403689', 'status' => 'Negeri', 'alamat' => 'Wadonggo, Kec. Tinanggea, Kab. Konawe Selatan', 'akreditasi' => 'C', 'latitude' => -4.47059542, 'longitude' => 122.27286986, 'img' => 'sdn13tinanggea.jpg'], // [cite: 14]
            ['id' => 26, 'jenjang_id' => 3, 'nama_sekolah' => 'SD NEGERI 9 TINANGGEA', 'npsn' => '40401963', 'status' => 'Negeri', 'alamat' => 'Jl. Poros Pelabuhan Torokeku, Kec. Tinanggea, Kab. Konawe Selatan', 'akreditasi' => 'C', 'latitude' => -4.48098684, 'longitude' => 122.25447714, 'img' => 'sdn9tinanggea.jpg'], // [cite: 15]
            ['id' => 27, 'jenjang_id' => 5, 'nama_sekolah' => 'SMP NEGERI SATU ATAP 19 KONAWE SELATAN', 'npsn' => '40405024', 'status' => 'Negeri', 'alamat' => 'Bungin Permai, Kec. Tinanggea, Kab. Konawe Selatan', 'akreditasi' => 'C', 'latitude' => -4.48987200, 'longitude' => 122.21809400, 'img' => 'smpnsatap19konsel.jpg'], // [cite: 16]
            ['id' => 28, 'jenjang_id' => 5, 'nama_sekolah' => 'SMP SWASTA WAHDAH ISLAMIYAH', 'npsn' => '70010126', 'status' => 'Swasta', 'alamat' => 'Jl. Poros Tinanggea-Lapulu, Kec. Tinanggea, Kab. Konawe Selatan', 'akreditasi' => 'C', 'latitude' => -4.46427485, 'longitude' => 122.24062967, 'img' => 'smpswahdah.jpg'], // [cite: 16]
            ['id' => 29, 'jenjang_id' => 6, 'nama_sekolah' => 'MTSN 2 KONAWE SELATAN', 'npsn' => '40405999', 'status' => 'Negeri', 'alamat' => 'Jl. Jend. Sudirman No.69, Kec. Tinanggea, Kab. Konawe Selatan', 'akreditasi' => 'A', 'latitude' => -4.44026390, 'longitude' => 122.17996971, 'img' => 'mtsn2konsel.jpg'], // [cite: 17]
            ['id' => 30, 'jenjang_id' => 7, 'nama_sekolah' => 'SMAN 19 KONAWE SELATAN', 'npsn' => '40405054', 'status' => 'Negeri', 'alamat' => 'Jl. Tenggiri No.1, Kec. Tinanggea, Kab. Konawe Selatan', 'akreditasi' => 'B', 'latitude' => -4.46725095, 'longitude' => 122.29369959, 'img' => 'sman19konsel.jpg'], // [cite: 18]
            ['id' => 31, 'jenjang_id' => 7, 'nama_sekolah' => 'SMAN 1 KONAWE SELATAN', 'npsn' => '40401877', 'status' => 'Negeri', 'alamat' => 'Jl. RA Kartini No.420, Kec. Tinanggea, Kab. Konawe Selatan', 'akreditasi' => 'A', 'latitude' => -4.46155176, 'longitude' => 122.23293754, 'img' => 'sman1konsel.jpg'], // [cite: 19]
            ['id' => 32, 'jenjang_id' => 3, 'nama_sekolah' => 'SD NEGERI 1 WAWONII BARAT', 'npsn' => '40400330', 'status' => 'Negeri', 'alamat' => 'Jl. Poros Pelabuhan Langara, Kec. Wawonii Barat, Kab. Konawe Kepulauan', 'akreditasi' => 'B', 'latitude' => -4.02831500, 'longitude' => 122.98916600, 'img' => 'sdn1wawoniibarat.jpg'], // [cite: 20]
            ['id' => 33, 'jenjang_id' => 3, 'nama_sekolah' => 'SD NEGERI 2 WAWONII BARAT', 'npsn' => '40400526', 'status' => 'Negeri', 'alamat' => 'Jl. Poros Langara-Lansilowo, Kec. Wawonii Barat, Kab. Konawe Kepulauan', 'akreditasi' => 'A', 'latitude' => -4.02237900, 'longitude' => 122.99854000, 'img' => 'sdn2wawoniibarat.jpg'], // [cite: 21]
            ['id' => 34, 'jenjang_id' => 3, 'nama_sekolah' => 'SD NEGERI 3 WAWONII BARAT', 'npsn' => '40403098', 'status' => 'Negeri', 'alamat' => 'Jl. Pelabuhan Kel. Langara Laut, Kec. Wawonii Barat, Kab. Konawe Kepulauan', 'akreditasi' => 'B', 'latitude' => -4.02332900, 'longitude' => 122.99038500, 'img' => 'sdn3wawoniibarat.jpg'], // [cite: 22]
            ['id' => 35, 'jenjang_id' => 3, 'nama_sekolah' => 'SD NEGERI 4 WAWONII BARAT', 'npsn' => '40400177', 'status' => 'Negeri', 'alamat' => 'Lamoluo, Kec. Wawonii Barat, Kab. Konawe Kepulauan', 'akreditasi' => 'B', 'latitude' => -4.02774600, 'longitude' => 122.98994400, 'img' => 'sdn4wawoniibarat.jpg'], // [cite: 22]
            ['id' => 36, 'jenjang_id' => 3, 'nama_sekolah' => 'SD NEGERI 5 WAWONII BARAT', 'npsn' => '40400305', 'status' => 'Negeri', 'alamat' => 'Jl. Poros Langara-Lansilowo, Kec. Wawonii Barat, Kab. Konawe Kepulauan', 'akreditasi' => 'C', 'latitude' => -4.02304407, 'longitude' => 122.99065672, 'img' => 'sdn5wawoniibarat.jpg'], // [cite: 23]
            ['id' => 37, 'jenjang_id' => 3, 'nama_sekolah' => 'SD NEGERI 6 WAWONII BARAT', 'npsn' => '40400159', 'status' => 'Negeri', 'alamat' => 'Matabaho, Kec. Wawonii Barat, Kab. Konawe Kepulauan', 'akreditasi' => 'C', 'latitude' => -4.03540785, 'longitude' => 122.99168705, 'img' => 'sdn6wawoniibarat.jpg'], // [cite: 24]
            ['id' => 38, 'jenjang_id' => 3, 'nama_sekolah' => 'SD NEGERI 7 WAWONII BARAT', 'npsn' => '40400169', 'status' => 'Negeri', 'alamat' => 'Desa Lanowatu, Kec. Wawonii Barat, Kab. Konawe Kepulauan', 'akreditasi' => 'C', 'latitude' => -4.03424900, 'longitude' => 122.99155200, 'img' => 'sdn7wawoniibarat.jpg'], // [cite: 25]
            ['id' => 39, 'jenjang_id' => 5, 'nama_sekolah' => 'SMP NEGERI 2 WAWONII BARAT', 'npsn' => '40404239', 'status' => 'Negeri', 'alamat' => 'Jl. Poros Langara-Lampeapi KM 3, Kec. Wawonii Barat, Kab. Konawe Kepulauan', 'akreditasi' => 'C', 'latitude' => -4.04691175, 'longitude' => 122.98780074, 'img' => 'smpn2wawoniibarat.jpg'], // [cite: 26]
            ['id' => 40, 'jenjang_id' => 5, 'nama_sekolah' => 'SMP NEGERI 3 WAWONII BARAT', 'npsn' => '40404084', 'status' => 'Negeri', 'alamat' => 'Jl. Poros Desa Wawolaa, Kec. Wawonii Barat, Kab. Konawe Kepulauan', 'akreditasi' => 'C', 'latitude' => -4.01727600, 'longitude' => 123.04742400, 'img' => 'smpn3wawoniibarat.jpg'], // [cite: 27]
            ['id' => 41, 'jenjang_id' => 5, 'nama_sekolah' => 'SMP NEGERI 4 WAWONII BARAT', 'npsn' => '69931771', 'status' => 'Negeri', 'alamat' => 'Desa Matabaho, Kec. Wawonii Barat, Kab. Konawe Kepulauan', 'akreditasi' => 'B', 'latitude' => -4.03694500, 'longitude' => 123.01894600, 'img' => 'smpn4wawoniibarat.jpg'], // [cite: 28]
            ['id' => 42, 'jenjang_id' => 7, 'nama_sekolah' => 'SMAN 1 WAWONII', 'npsn' => '40400243', 'status' => 'Negeri', 'alamat' => 'Desa Mata Langara, Kec. Wawonii Barat, Kab. Konawe Kepulauan', 'akreditasi' => 'B', 'latitude' => -4.03015441, 'longitude' => 122.98621162, 'img' => 'sman1wawonii.jpg'], // [cite: 29]
            ['id' => 43, 'jenjang_id' => 3, 'nama_sekolah' => 'SD NEGERI 1 TORONIPA', 'npsn' => '40400512', 'status' => 'Negeri', 'alamat' => 'SDN 1 Toronipa, Kec. Soropia, Kab. Konawe', 'akreditasi' => 'B', 'latitude' => -3.90149700, 'longitude' => 122.64357600, 'img' => 'sdn1toronipa.jpg'], // [cite: 29]
            ['id' => 44, 'jenjang_id' => 3, 'nama_sekolah' => 'SD NEGERI 3 TORONIPA', 'npsn' => '40400185', 'status' => 'Negeri', 'alamat' => 'Kelurahan Toronipa, Kec. Soropia, Kab. Konawe', 'akreditasi' => 'B', 'latitude' => -3.91033500, 'longitude' => 122.65997000, 'img' => 'sdn3toronipa.jpg'], // [cite: 30]
            ['id' => 45, 'jenjang_id' => 5, 'nama_sekolah' => 'SMP NEGERI 31 KONAWE SELATAN', 'npsn' => '40403328', 'status' => 'Negeri', 'alamat' => 'Jalan Mangga Butu No.1, Kec. Tinanggea, Kab. Konawe Selatan', 'akreditasi' => 'B', 'latitude' => -4.46921362, 'longitude' => 122.29572998, 'img' => 'smpn31konsel.jpg'], // [cite: 31]
            ['id' => 46, 'jenjang_id' => 5, 'nama_sekolah' => 'SMP NEGERI 1 WAWONII BARAT', 'npsn' => '40400230', 'status' => 'Negeri', 'alamat' => 'Jl. Poros Langara, Kec. Wawonii Barat, Kab. Konawe Kepulauan', 'akreditasi' => 'B', 'latitude' => -4.02324900, 'longitude' => 122.99086500, 'img' => 'smpn1wawoniibarat.jpg'], // [cite: 32]
            ['id' => 47, 'jenjang_id' => 3, 'nama_sekolah' => 'SD NEGERI 4 TINANGGEA', 'npsn' => '40402110', 'status' => 'Negeri', 'alamat' => 'Desa Lapoa, Kec. Tinanggea, Kab. Konawe Selatan', 'akreditasi' => 'B', 'latitude' => -4.44076450, 'longitude' => 122.18069900, 'img' => 'sdn4tinanggea.jpg'], // [cite: 32]
            ['id' => 48, 'jenjang_id' => 14, 'nama_sekolah' => 'LKP ANAK NUSANTARA', 'npsn' => 'K9981131', 'status' => 'Swasta', 'alamat' => 'Jln. Poros Tinanggea - Lalembuu', 'akreditasi' => null, 'latitude' => null, 'longitude' => null, 'img' => 'lkpanaknusantara.jpg'], // [cite: 33]
            ['id' => 49, 'jenjang_id' => 14, 'nama_sekolah' => 'LKP IZDIHAR', 'npsn' => 'K5668616', 'status' => 'Swasta', 'alamat' => 'Jln. Abd.Silondae', 'akreditasi' => null, 'latitude' => null, 'longitude' => null, 'img' => 'lkpizdihar.jpg'], // [cite: 33]
            ['id' => 50, 'jenjang_id' => 12, 'nama_sekolah' => 'PKBM ANAK NUSANTARA', 'npsn' => 'P9934396', 'status' => 'Swasta', 'alamat' => 'Jl. Jend. Sodirman Blok B', 'akreditasi' => 'B', 'latitude' => null, 'longitude' => null, 'img' => 'pkbmanaknusantara.jpg'], // [cite: 34]
            ['id' => 51, 'jenjang_id' => 12, 'nama_sekolah' => 'PKBM ARYA LINGUANGE MANDIRI', 'npsn' => 'P9934831', 'status' => 'Swasta', 'alamat' => 'Desa Bungin Permai', 'akreditasi' => 'C', 'latitude' => null, 'longitude' => null, 'img' => 'pkbmaryalinguangemandiri.jpg'], // [cite: 34]
            ['id' => 52, 'jenjang_id' => 12, 'nama_sekolah' => 'PKBM WAJAR', 'npsn' => 'P9998282', 'status' => 'Swasta', 'alamat' => 'Jln. Poros Lasuai', 'akreditasi' => 'C', 'latitude' => null, 'longitude' => null, 'img' => 'pkbmwajar.jpg'], // [cite: 35]
            ['id' => 53, 'jenjang_id' => 13, 'nama_sekolah' => 'SKB TINANGGEA', 'npsn' => 'P9959761', 'status' => 'Negeri', 'alamat' => 'Jln.Poros Andoolo - Tinanggea', 'akreditasi' => 'C', 'latitude' => -4.43970000, 'longitude' => 122.22860000, 'img' => 'skbtinanggea.jpg'], // [cite: 35]
            ['id' => 54, 'jenjang_id' => 12, 'nama_sekolah' => 'PKBM SAURI LEAMA', 'npsn' => 'P9908576', 'status' => 'Swasta', 'alamat' => 'Saponda Kecamatan Soropia', 'akreditasi' => 'B', 'latitude' => null, 'longitude' => null, 'img' => 'pkbmsaurileama.jpg'], // [cite: 35]
            ['id' => 55, 'jenjang_id' => 12, 'nama_sekolah' => 'PKBM MADANI', 'npsn' => 'P9959831', 'status' => 'Swasta', 'alamat' => 'Desa Langara Tanjung Batu', 'akreditasi' => 'B', 'latitude' => -4.01808475, 'longitude' => 122.99742229, 'img' => 'pkbmmadani.jpg'], // [cite: 35]
            ['id' => 56, 'jenjang_id' => 12, 'nama_sekolah' => 'PKBM HANDAYANI', 'npsn' => 'P2964350', 'status' => 'Swasta', 'alamat' => 'JL. Langara', 'akreditasi' => 'B', 'latitude' => null, 'longitude' => null, 'img' => 'pkbmhandayani.jpg'], // [cite: 36]
            ['id' => 57, 'jenjang_id' => 13, 'nama_sekolah' => 'SKB WAWONII', 'npsn' => 'P9962961', 'status' => 'Negeri', 'alamat' => 'Jl. Poros Desa Pasir Putih', 'akreditasi' => 'C', 'latitude' => null, 'longitude' => null, 'img' => 'skbwawonii.jpg'], // [cite: 36]
            ['id' => 58, 'jenjang_id' => 1, 'nama_sekolah' => 'TK ANGIN MAMIRI', 'npsn' => '69761564', 'status' => 'Swasta', 'alamat' => 'MBATOI, SOROPIA', 'akreditasi' => 'B', 'latitude' => -3.90072300, 'longitude' => 122.58098900, 'img' => 'tkanginmamiri.jpg'], // [cite: 36]
            ['id' => 59, 'jenjang_id' => 1, 'nama_sekolah' => 'TK DHARMA WANITA', 'npsn' => '69761562', 'status' => 'Swasta', 'alamat' => 'DESA TORONIPA', 'akreditasi' => 'B', 'latitude' => null, 'longitude' => null, 'img' => 'tkdharmawanita.jpg'], // [cite: 36]
            ['id' => 60, 'jenjang_id' => 1, 'nama_sekolah' => 'TK MEKAR JAYA', 'npsn' => '69762354', 'status' => 'Swasta', 'alamat' => 'Desa Mekar', 'akreditasi' => 'B', 'latitude' => null, 'longitude' => null, 'img' => 'tkmekarjaya.jpg'], // [cite: 36]
            ['id' => 61, 'jenjang_id' => 1, 'nama_sekolah' => 'TK MUTIARA SAPONDA', 'npsn' => '70056365', 'status' => 'Swasta', 'alamat' => 'Desa Saponda', 'akreditasi' => null, 'latitude' => null, 'longitude' => null, 'img' => 'tkmutiarasaponda.jpg'], // [cite: 36]
            ['id' => 62, 'jenjang_id' => 1, 'nama_sekolah' => 'TK NEGERI SORUE JAYA', 'npsn' => '70037057', 'status' => 'Negeri', 'alamat' => 'Desa Sorue Jaya', 'akreditasi' => 'B', 'latitude' => null, 'longitude' => null, 'img' => 'tknegerisoruejaya.jpg'], // [cite: 36]
            ['id' => 63, 'jenjang_id' => 1, 'nama_sekolah' => 'TK PGRI LAMBESO', 'npsn' => '69771530', 'status' => 'Swasta', 'alamat' => 'DUSUN II BOKORI', 'akreditasi' => 'C', 'latitude' => null, 'longitude' => null, 'img' => 'tkpgrilambeso.jpg'], // [cite: 36]
            ['id' => 64, 'jenjang_id' => 1, 'nama_sekolah' => 'TK SINAR TELAGA', 'npsn' => '69902532', 'status' => 'Swasta', 'alamat' => 'Jl. Poros Toronipa-Soropia', 'akreditasi' => 'C', 'latitude' => null, 'longitude' => null, 'img' => 'tksinartelaga.jpg'], // [cite: 37]
            ['id' => 65, 'jenjang_id' => 1, 'nama_sekolah' => 'TK WONUA MANDARA', 'npsn' => '69762334', 'status' => 'Swasta', 'alamat' => 'SAWAPUDO', 'akreditasi' => 'B', 'latitude' => -3.89700100, 'longitude' => 122.60309200, 'img' => 'tkwonuamandara.jpg'], // [cite: 37]
            ['id' => 66, 'jenjang_id' => 1, 'nama_sekolah' => 'TKS ATOWATU', 'npsn' => '69761563', 'status' => 'Swasta', 'alamat' => 'POROS ATOWATU-SOROPIA', 'akreditasi' => 'C', 'latitude' => null, 'longitude' => null, 'img' => 'tksatowatu.jpg'], // [cite: 37]
            ['id' => 67, 'jenjang_id' => 1, 'nama_sekolah' => 'DHARMA WANITA', 'npsn' => '69797229', 'status' => 'Negeri', 'alamat' => 'JL. DRS. H. ABD SILONDAEA', 'akreditasi' => 'B', 'latitude' => -4.44040000, 'longitude' => 122.19560000, 'img' => 'dharmawanita.jpg'], // [cite: 37]
            ['id' => 68, 'jenjang_id' => 1, 'nama_sekolah' => 'ISLAM AL-KAUTZAR', 'npsn' => '69797194', 'status' => 'Swasta', 'alamat' => 'JL. H.ABD.SILONDAE', 'akreditasi' => 'B', 'latitude' => -4.46197598, 'longitude' => 122.22643182, 'img' => 'islamalkautzar.jpg'], // [cite: 38]
            ['id' => 69, 'jenjang_id' => 11, 'nama_sekolah' => 'KB Tunas Mekar Lapoa', 'npsn' => '69952610', 'status' => 'Swasta', 'alamat' => 'Blok B, Desa Lapoa', 'akreditasi' => 'B', 'latitude' => -4.44003900, 'longitude' => 122.17945100, 'img' => 'kbtunasmekarlapoa.jpg'], // [cite: 38]
            ['id' => 70, 'jenjang_id' => 1, 'nama_sekolah' => 'PRATAMA WIDYALAYA DHARMA SANTI LAPOA', 'npsn' => '70033764', 'status' => 'Swasta', 'alamat' => 'JL. POROS LAPOA-BOMBANA KEC. TINANGGEA', 'akreditasi' => 'C', 'latitude' => -4.43990000, 'longitude' => 122.17480000, 'img' => 'pratamawidyalaya.jpg'], // [cite: 39]
            ['id' => 71, 'jenjang_id' => 2, 'nama_sekolah' => 'RA AT TAQWA', 'npsn' => '69757116', 'status' => 'Swasta', 'alamat' => 'JLN. JEND. SUDIRMAN', 'akreditasi' => 'A', 'latitude' => -4.43940803, 'longitude' => 122.16846840, 'img' => 'raattaqwa.jpg'], // [cite: 39]
            ['id' => 72, 'jenjang_id' => 2, 'nama_sekolah' => 'RA/BA/TA AISYIYAH PALOTAWO', 'npsn' => '69751773', 'status' => 'Swasta', 'alamat' => 'DESA PALOTAWO', 'akreditasi' => 'C', 'latitude' => -4.38222500, 'longitude' => 122.21568200, 'img' => 'raaisyiyahpalotawo.jpg'], // [cite: 39]
            ['id' => 73, 'jenjang_id' => 2, 'nama_sekolah' => 'RA/BA/TA AZ ZAHRA', 'npsn' => '69751774', 'status' => 'Swasta', 'alamat' => 'JLN. YOS SUDARSO', 'akreditasi' => 'C', 'latitude' => -4.47621800, 'longitude' => 122.21964500, 'img' => 'raazzahra.jpg'], // [cite: 40]
            ['id' => 74, 'jenjang_id' => 2, 'nama_sekolah' => 'RA/BA/TA MIFTAHUL ULUM', 'npsn' => '69751775', 'status' => 'Swasta', 'alamat' => 'DESA MOLO INDAH', 'akreditasi' => 'C', 'latitude' => -4.46813658, 'longitude' => 122.29303164, 'img' => 'ramiftahululum.jpg'], // [cite: 40]
            ['id' => 75, 'jenjang_id' => 2, 'nama_sekolah' => 'RA/BA/TA ULUL ALBAAB', 'npsn' => '69751777', 'status' => 'Swasta', 'alamat' => 'DESA MATANDAHI', 'akreditasi' => 'C', 'latitude' => -4.46914982, 'longitude' => 122.31637271, 'img' => 'raululalbaab.jpg'], // [cite: 40]
            ['id' => 76, 'jenjang_id' => 1, 'nama_sekolah' => 'TK CEMPAKA ASINGI', 'npsn' => '69852538', 'status' => 'Swasta', 'alamat' => 'JL. POROS ANDOOLO - TINANGGEA', 'akreditasi' => 'B', 'latitude' => null, 'longitude' => null, 'img' => 'tkcempakaasingi.jpg'], // [cite: 41]
            ['id' => 77, 'jenjang_id' => 11, 'nama_sekolah' => 'KB Bunga Karang', 'npsn' => '69976993', 'status' => 'Swasta', 'alamat' => 'Desa Langara Tangung Batu Kecamatan Wawonii Barat', 'akreditasi' => 'B', 'latitude' => null, 'longitude' => null, 'img' => 'kbbungakarang.jpg'], // [cite: 41]
            ['id' => 78, 'jenjang_id' => 11, 'nama_sekolah' => 'KB MATABAHO', 'npsn' => '69978313', 'status' => 'Swasta', 'alamat' => 'Desa Matabaho Kec. Wawonii Barat Kab. Konawe Kepulauan', 'akreditasi' => 'C', 'latitude' => -4.03679640, 'longitude' => 123.01948320, 'img' => 'kbmatabaho.jpg'], // [cite: 42]
            ['id' => 79, 'jenjang_id' => 10, 'nama_sekolah' => 'PAUD Cendekia', 'npsn' => '69935135', 'status' => 'Swasta', 'alamat' => 'Jl. Poros Langara Wawolaa', 'akreditasi' => 'B', 'latitude' => null, 'longitude' => null, 'img' => 'paudcendekia.jpg'], // [cite: 42]
            ['id' => 80, 'jenjang_id' => 10, 'nama_sekolah' => 'PAUD Ceria Handayani', 'npsn' => '69919599', 'status' => 'Swasta', 'alamat' => 'Jl. Poros Wawobili', 'akreditasi' => 'C', 'latitude' => -4.01054900, 'longitude' => 123.03276600, 'img' => 'paudceriahandayani.jpg'], // [cite: 43]
            ['id' => 81, 'jenjang_id' => 10, 'nama_sekolah' => 'PAUD Ika Putri Madani', 'npsn' => '69919346', 'status' => 'Swasta', 'alamat' => 'Jl. Poros Langara-Lampeapi', 'akreditasi' => 'A', 'latitude' => -4.03233171, 'longitude' => 122.99115979, 'img' => 'paudikaputrimadani.jpg'], // [cite: 43]
            ['id' => 82, 'jenjang_id' => 2, 'nama_sekolah' => 'RA Ummu Salamah', 'npsn' => '70050506', 'status' => 'Swasta', 'alamat' => 'Jl. Abdullah RT.004/RW.002', 'akreditasi' => 'C', 'latitude' => null, 'longitude' => null, 'img' => 'raummusalamah.jpg'], // [cite: 44]
            ['id' => 83, 'jenjang_id' => 1, 'nama_sekolah' => 'TK AL FADILAH', 'npsn' => '69979190', 'status' => 'Swasta', 'alamat' => 'Desa Bukit Permai Kecamatan Wawonii Barat', 'akreditasi' => 'C', 'latitude' => null, 'longitude' => null, 'img' => 'tkalfadilah.jpg'], // [cite: 44]
            ['id' => 84, 'jenjang_id' => 1, 'nama_sekolah' => 'TK AFI', 'npsn' => '69918544', 'status' => 'Swasta', 'alamat' => 'Jl. Langara Wawolaa', 'akreditasi' => 'B', 'latitude' => -4.02367700, 'longitude' => 122.99615830, 'img' => 'tkafi.jpg'], // [cite: 44]
            ['id' => 85, 'jenjang_id' => 1, 'nama_sekolah' => 'TK BAHARI', 'npsn' => '69761631', 'status' => 'Swasta', 'alamat' => 'JL. H. Abdullah', 'akreditasi' => 'C', 'latitude' => -4.02034630, 'longitude' => 122.99327780, 'img' => 'tkbahari.jpg'], // [cite: 45]
            ['id' => 86, 'jenjang_id' => 1, 'nama_sekolah' => 'TK HARAPAN BANGSA', 'npsn' => '69917973', 'status' => 'Swasta', 'alamat' => 'Jl. Poros Langara Iwawo', 'akreditasi' => 'C', 'latitude' => -4.02974310, 'longitude' => 122.98993300, 'img' => 'tkharapanbangsa.jpg'], // [cite: 45]
            ['id' => 87, 'jenjang_id' => 1, 'nama_sekolah' => 'TK NEGERI PEMBINA WAWONII BARAT', 'npsn' => '69932594', 'status' => 'Negeri', 'alamat' => 'Jl. Poros Langara', 'akreditasi' => 'B', 'latitude' => null, 'longitude' => null, 'img' => 'tknegeripembinawawoniibarat.jpg'], // [cite: 46]
            ['id' => 88, 'jenjang_id' => 1, 'nama_sekolah' => 'TK Waly Mekar', 'npsn' => '69967181', 'status' => 'Swasta', 'alamat' => 'Desa Kawa-Kawali Kec Wawonii Barat', 'akreditasi' => 'C', 'latitude' => -4.01007530, 'longitude' => 123.02975750, 'img' => 'tkwalymekar.jpg'], // [cite: 46]
            ['id' => 89, 'jenjang_id' => 7, 'nama_sekolah' => 'SMA NEGERI 3 KENDARI', 'npsn' => '40402617', 'status' => 'Negeri', 'alamat' => 'Jl. Ra. Kartini No.127, Kessilampe, Kec. Kendari, Kota Kendari, Sulawesi Tenggara 93126, Indonesia', 'akreditasi' => 'A', 'latitude' => -3.97615011, 'longitude' => 122.59930901, 'img' => '1783041989_sman3kendari.jpg'], // [cite: 47]
        ];

        foreach ($dataSekolah as $item) {
            Sekolah::create($item);
        }

        $this->command->info('Sukses! Semua data sekolah berhasil dimasukkan beserta koordinat aslinya.');
    }
}